# -*- coding: utf-8 -*-
"""DDR_data_transform.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WeIAwp1ZOgxg_u7lt-H8zhxx7WdyyqDz
"""

import numpy as np
import seaborn as sns
import pandas as pd
import matplotlib
import matplotlib.pyplot as plt

from google.colab import drive
drive.mount('/content/drive')

df = pd.read_excel("/content/drive/MyDrive/Data/Dual_barcode/Two_barcode_DDR/Analyzed_U6DDR/analyzed_U6DDR_naive_1_w_annotation.xlsx")
df.head(5)

df_s=df[['ID','Symbol','D_length', 'I_length']]

df_s.info()

len(df_s["Symbol"].unique())

len(df_s.loc[(df_s['D_length'].isnull() & df_s['I_length'].isnull())])

stats = pd.DataFrame([])
stats_pct = pd.DataFrame([])
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)

for i in df_s["Symbol"].unique():
  gene = str(i)
  df_sub = df_s.loc[(df_s['Symbol']==i)]
  Micro_D = len(df_sub.loc[(df_sub['D_length'] < 3)])
  Mid_D = len(df_sub.loc[(df_sub['D_length'] >= 3) & (df_sub['D_length'] <= 10)])
  Large_D = len(df_sub.loc[(df_sub['D_length'] > 10)])
  Ins = df_sub["I_length"].notna().sum()
  Direct = len(df_sub.loc[(df_sub['D_length'].isnull() & df_sub['I_length'].isnull())])

  row = pd.DataFrame({"gene":[gene], "Large_D(>10bps)":[Large_D], "Mid_D(3-10bps)":[Mid_D], "Micro_D(<3bps)":[Micro_D],
                      "Direct(or_noDSB)":[Direct], "Insertion":[Ins]})
  stats = stats.append(row,ignore_index=True)

  Total = Micro_D + Mid_D + Large_D + Ins + Direct
  Micro_D_pct = -Micro_D/Total
  Mid_D_pct = -Mid_D/Total
  Large_D_pct = -Large_D/Total
  Ins_pct = Ins/Total
  Direct_pct = Direct/Total

  row_pct = pd.DataFrame({"gene":[gene], "Large_D(>10bps)":[Large_D_pct], "Mid_D(3-10bps)":[Mid_D_pct], "Micro_D(<3bps)":[Micro_D_pct],
                      "Direct(or_noDSB)":[Direct_pct], "Insertion":[Ins_pct]})
  stats_pct = stats_pct.append(row_pct,ignore_index=True)

stats.to_csv('U6DDR_naive_1.csv')
stats_pct.to_csv('U6DDR_naive_1_pct.csv')

from google.colab import files
files.download("U6DDR_naive_1.csv")
files.download("U6DDR_naive_1_pct.csv")

stats_pct.info()

stats_pct = pd.read_csv ("/content/drive/MyDrive/Data/Dual_barcode/Two_barcode_DDR/Analyzed_U6DDR/U6DDR_Cycling_CLV_pct_average.csv")
stats_pct.set_index("gene", inplace=True)
stats_pct.head(5)

# stats_pct.set_index("gene", inplace=True)
# stats_pct.head(5)

from google.colab import files

sns_plot = sns.clustermap(stats_pct,
               cmap="coolwarm",
               yticklabels=True,
               col_cluster=False,
               cbar_pos=(0.02, 0.85, 0.02, 0.18))
hmap = sns_plot.ax_heatmap.get_position()
plt.setp(sns_plot.ax_heatmap.yaxis.get_majorticklabels(), fontsize=6)
sns_plot.ax_heatmap.set_position([hmap.x0, hmap.y0, hmap.width*0.25, hmap.height])
col = sns_plot.ax_col_dendrogram.get_position()
sns_plot.ax_col_dendrogram.set_position([col.x0, col.y0, col.width*0.25, col.height*0.5])

plt.show()

sns_plot.savefig("U6DDR_Cycling_V2.png", dpi=600)

files.download("U6DDR_Cycling_V2.png")

