# -*- coding: utf-8 -*-
"""Cigar_Mapping_Reading.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ek2vX7233jLlI2wyfEKT45QXDCOW46AI
"""

import numpy as np
import pandas as pd
pd.options.mode.chained_assignment = None
import os

def mut_extraction(file):
    stat = file.copy()
    stat[["D_length", "D_location", "I_length", "I_location"]] = ""
    for i, annotation in enumerate(file["Cigar"]):
        cc = 0
        idx0 = 0 #event location
        if annotation != "*":
            if annotation[2] == "I":
                r_annotation = annotation[3:-3] # remove constant regions
                for c, a in enumerate(r_annotation):
                    if a.isalpha():
                        l = int(r_annotation[cc:c]) #event length
                        if a == "M":
                            idx0 += l

                        else:
                            # initiate new cells
                            if len(stat[a + "_length"].iloc[i]) == 0:
                                stat[a + "_length"].iloc[i] = []
                            if len(stat[a + "_location"].iloc[i]) == 0:
                                stat[a + "_location"].iloc[i] = []

                            # misalignment information
                            stat[a + "_length"].iloc[i].append(l)
                            if a =="D":
                                stat[a + "_location"].iloc[i].append([idx0, idx0 + l])
                                idx0 += l
                            if a == "I":
                                stat[a + "_location"].iloc[i].append([idx0])

                        cc = c + 1

    return stat

baseFolder = "U6DDR_annotation/"

fileName = os.listdir(baseFolder)
for f in fileName:
    file = pd.read_csv(baseFolder+f)

    file.dropna(inplace=True)
    stat = mut_extraction(file)

    stat.to_csv("Analyzed_U6DDR/analyzed_"+f)